version: "3.8"

volumes:
    postgres_data:

services:
    backend:
        build: 
            context: ./backend
            dockerfile: backend.dockerfile
        command: uvicorn --reload --host 0.0.0.0 --port 8000 main:app
        volumes:
            - ./backend/app:/app
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db
    
    frontend:
        build:
            context: ./frontend
            dockerfile: frontend.dockerfile
        command: npm run serve
        volumes:
            - ./frontend:/app
        depends_on:
            - db
        ports:
            - 8080:8080
        env_file:
            - ./.env

    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
        ports:
            - 5432:5432

