"""fix user_id to avatar

Revision ID: 025e0a77cd27
Revises: 0dd0cae23704
Create Date: 2021-06-08 17:36:31.124995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025e0a77cd27'
down_revision = '0dd0cae23704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'avatar', 'm_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'avatar', type_='foreignkey')
    # ### end Alembic commands ###
